export const AUTH_USER_START = 'AUTH_USER_START';
export const AUTH_USER_FAILED = 'AUTH_USER_FAILED';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_SAGA = 'AUTH_USER_SAGA';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_LOGOUT_START = 'AUTH_LOGOUT_START';
export const AUTH_LOGOUT_SAGA = 'AUTH_LOGOUT_SAGA';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_CRYPTO_DATA_START = 'FETCH_CRYPTO_DATA_START';
export const FETCH_CRYPTO_DATA_FAIL = 'FETCH_CRYPTO_DATA_FAIL';
export const FETCH_CRYPTO_DATA_SUCCESS= 'FETCH_CRYPTO_DATA_SUCCESS';
export const FETCH_CRYPTO_DATA_SAGA = 'FETCH_CRYPTO_DATA_SAGA';

export const PURCHASE_CRYPTO_START = 'PURCHASE_CRYPTO_START';
export const PURCHASE_CRYPTO_SUCCESS = 'PURCHASE_CRYPTO_SUCCESS';
export const PURCHASE_CRYPTO_FAIL = 'PURCHASE_CRYPTO_FAIL';
export const PURCHASE_INIT=  'PURCHASE_INIT';
export const PURCHASE_CRYPTO_SAGA = 'PURCHASE_CRYPTO_SAGA';

export const FETCH_TRANSACTIONS_SAGA = 'FETCH_TRANSACTIONS_SAGA';
export const FETCH_TRANSACTIONS_START = 'FETCH_TRANSACTIONS_START';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_FAIL= 'FETCH_TRANSACTIONS_FAIL';

export const UPDATE_TRANSACTION_START = 'UPDATE_TRANSACTION_START';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_FAIL= 'UPDATE_TRANSACTION_FAIL';
export const UPDATE_TRANSACTION_SAGA = 'UPDATE_TRANSACTION_SAGA';

export const DELETE_TRANSACTION_START = 'DELETE_TRANSACTION_START';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_FAIL= 'DELETE_TRANSACTION_FAIL';
export const DELETE_TRANSACTION_SAGA = 'DELETE_TRANSACTION_SAGA';


export const SIGN_UP_USER_START = 'SIGN_UP_USER_START';
export const SIGN_UP_USER_FAIL = 'SIGN_UP_USER_FAIL';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_SAGA = 'SIGN_UP_USER_SAGA';




